name: ci
on:
  push:
    branches: master      
    paths-ignore:
      - README.md
      - README_CN.md
      - LICENSE
  pull_request:
    paths-ignore:
      - README.md
      - README_CN.md
      - LICENSE

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2  # 使用 v2 版本的 Flutter action
        with:
            channel: stable
            flutter-version: 1.1.x
      - name: Build Flutter application for Android
        run: flutter build apk --split-per-abi
      - name: Rename armeabi-v7a APK
        run: mv build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk android-armeabi-v7a.apk
      - name: Rename arm64-v8a APK
        run: mv build/app/outputs/flutter-apk/app-arm64-v8a-release.apk android-arm64-v8a.apk
      - name: Rename x86_64 APK
        run: mv build/app/outputs/flutter-apk/app-x86_64-release.apk android-x86_64.apk
      - name: Upload armeabi-v7a APK
        uses: actions/upload-artifact@v4
        with:
          name: android-armeabi-v7a.apk
          path: android-armeabi-v7a.apk
      - name: Upload arm64-v8a APK
        uses: actions/upload-artifact@v4
        with:
          name: android-arm64-v8a.apk
          path: android-arm64-v8a.apk
      - name: Upload x86_64 APK
        uses: actions/upload-artifact@v4
        with:
          name: android-x86_64.apk
          path: android-x86_64.apk